<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU79RkxJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU79RkxJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU79RkxJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU79RkxJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU79RkxJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'U79RkxJ',
    'container.build_id' => 'c956ec68',
    'container.build_time' => 1596111689,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU79RkxJ');
