<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGOlxWqc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGOlxWqc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGOlxWqc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGOlxWqc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGOlxWqc\App_KernelDevDebugContainer([
    'container.build_hash' => 'GOlxWqc',
    'container.build_id' => 'ed12e435',
    'container.build_time' => 1596031745,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGOlxWqc');
