<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUN4Jvg0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUN4Jvg0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUN4Jvg0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUN4Jvg0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUN4Jvg0\App_KernelDevDebugContainer([
    'container.build_hash' => 'UN4Jvg0',
    'container.build_id' => 'f76b0755',
    'container.build_time' => 1595850642,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUN4Jvg0');
